/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_external_FaceBeautify */

#ifndef _Included_io_agora_external_FaceBeautify
#define _Included_io_agora_external_FaceBeautify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_agora_external_FaceBeautify
 * Method:    doStartFB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_agora_external_FaceBeautify_doStartFB
  (JNIEnv *, jobject);

/*
 * Class:     io_agora_external_FaceBeautify
 * Method:    doStopFB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_agora_external_FaceBeautify_doStopFB
  (JNIEnv *, jobject);

/*
 * Class:     io_agora_external_FaceBeautify_doSetLighteningFactor
 * Method:    doStopFB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_agora_external_FaceBeautify_doSetLighteningFactor
  (JNIEnv *, jobject, jfloat factor);


  /*
   * Class:     io_agora_external_FaceBeautify_doSetSmoothnessFactor
   * Method:    doStopFB
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL Java_io_agora_external_FaceBeautify_doSetSmoothnessFactor
    (JNIEnv *, jobject, jint flactor);

#ifdef __cplusplus
}
#endif
#endif
